services:
  postgres:
    image: postgres:16-alpine
    container_name: mini-food-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: food_password2026
      POSTGRES_DB: mini_food
    ports:
      - "5432:5432"
    volumes:
      - mini_food_postgres_data:/var/lib/postgresql/data

volumes:
  mini_food_postgres_data:
